export const moviesData = [
  {
    _id: '001',
    country: 'Россия',
    director: 'Неисзвестный 1',
    duration: 120,
    year: '2020',
    description: 'Описание этого фильма',
    image:
      'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/Lake-Baikal.jpg',
    nameRU: '33 слова о дизайне',
    nameEN: 'Name 1',
    trailerLink: 'https://youtu.be/9eF3kupk-yg',
  },
  {
    _id: '002',
    country: 'Россия',
    director: 'Неисзвестный 2',
    duration: 80,
    year: '2021',
    description: 'Описание этого фильма',
    image:
      'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/Iguassu-Falls.jpg',
    nameRU: 'Название очень длинное название фильма 2',
    nameEN: 'Name 2',
    trailerLink: 'https://youtu.be/9eF3kupk-yg',
  },
  {
    _id: '003',
    country: 'Россия',
    director: 'Неисзвестный 3',
    duration: 60,
    year: '2022',
    description: 'Описание этого фильма',
    image:
      'https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg',
    nameRU: 'Название 3',
    nameEN: 'Name 3',
    trailerLink: 'https://youtu.be/9eF3kupk-yg',
  },
  {
    _id: '004',
    country: 'Россия',
    director: 'Неисзвестный 4',
    duration: 139,
    year: '2022',
    description: 'Описание этого фильма',
    image:
      'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/kawachi-touen.jpg',
    nameRU: 'Название 4',
    nameEN: 'Name 4',
    trailerLink: 'https://youtu.be/9eF3kupk-yg',
  },
  {
    _id: '005',
    country: 'Россия',
    director: 'Неисзвестный 5',
    duration: 32,
    year: '2019',
    description: 'Описание этого фильма',
    image:
      'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/Geirangerfjord.jpg',
    nameRU: 'Название 5',
    nameEN: 'Name 5',
    trailerLink: 'https://youtu.be/9eF3kupk-yg',
  },
  // {
  //   _id: '003',
  //   country: 'Россия',
  //   director: 'Неисзвестный 3',
  //   duration: 60,
  //   year: '2022',
  //   description: 'Описание этого фильма',
  //   image:
  //     'https://planetofhotels.com/guide/sites/default/files/styles/node__blog_post__bp_banner/public/2021-01/Kirkjufell-volcano.jpg',
  //   nameRU: 'Название 3',
  //   nameEN: 'Name 3',
  //   trailerLink: 'https://youtu.be/9eF3kupk-yg',
  // },
  // {
  //   _id: '004',
  //   country: 'Россия',
  //   director: 'Неисзвестный 4',
  //   duration: 139,
  //   year: '2022',
  //   description: 'Описание этого фильма',
  //   image:
  //     'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/kawachi-touen.jpg',
  //   nameRU: 'Название 4',
  //   nameEN: 'Name 4',
  //   trailerLink: 'https://youtu.be/9eF3kupk-yg',
  // },
  // {
  //   _id: '005',
  //   country: 'Россия',
  //   director: 'Неисзвестный 5',
  //   duration: 32,
  //   year: '2019',
  //   description: 'Описание этого фильма',
  //   image:
  //     'https://planetofhotels.com/guide/sites/default/files/styles/paragraph__text_with_image___twi_image/public/2021-01/Geirangerfjord.jpg',
  //   nameRU: 'Название 5',
  //   nameEN: 'Name 5',
  //   trailerLink: 'https://youtu.be/9eF3kupk-yg',
  // },
]
